# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'calculator-azure-ci'
  dockerHubRegistry: 'raviteja191'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        containerRegistry: 'docker.io'
        repository: $(dockerHubRegistry)/$(imageName)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
      env:
        DOCKERHUB_USERNAME: $(dockerHubRegistry)
        DOCKERHUB_PASSWORD: $(dockerHubPassword)